name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      # Checkout โค้ดจาก repository
      - uses: actions/checkout@v4
        with:
          submodules: true

      # ตั้งค่า pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      # ตั้งค่า Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.7'
          cache: 'pnpm'

      # ติดตั้ง dependencies และ build โปรเจกต์
      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      # ตรวจสอบว่า build output มี index.html
      - name: Check build output
        run: |
          ls -la dist
          if [ ! -f "dist/index.html" ] && [ ! -f "dist/Index.html" ]; then
            echo "Error: No default file (index.html or Index.html) found in dist folder"
            exit 1
          fi

      # ตั้งค่า AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # ปรับ region ตามที่คุณใช้ใน Amplify

      # Deploy ไป AWS Amplify
      - name: Deploy to AWS Amplify
        run: |
          npm install -g @aws-amplify/cli  # ติดตั้ง Amplify CLI
          amplify publish --yes  # Deploy โดยไม่ต้องยืนยัน
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        run: echo "Pull request closed, no deployment needed."
