name: Azure Static Web Apps CI/CD with pnpm for warongkon-blog

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: '18.20.7' # ปรับให้ตรงกับ Oryx ที่ใช้
=======
          node-version: '18.20.7'  # ปรับให้ตรงกับ Oryx ที่ใช้
>>>>>>> ea71a5ebe6d53e8a9bdf53ad81f084dcaaff375d
          cache: 'pnpm'

      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_RIVER_058F56A00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
          action: 'upload'
          app_location: '/'
          api_location: ''
          output_location: 'dist'
          app_build_command: 'pnpm run build' # ระบุคำสั่ง build แบบชัดเจน
=======
          action: "upload"
          app_location: "/"  
          api_location: ""  
          output_location: "dist"
          app_build_command: "pnpm run build"  # ระบุคำสั่ง build แบบชัดเจน
>>>>>>> ea71a5ebe6d53e8a9bdf53ad81f084dcaaff375d

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_RIVER_058F56A00 }}
<<<<<<< HEAD
          action: 'close'
=======
          action: "close"
>>>>>>> ea71a5ebe6d53e8a9bdf53ad81f084dcaaff375d
