name: Deploy to AWS Amplify

# เพิ่ม permissions เพื่อให้ GitHub Actions ใช้ OIDC
permissions:
  id-token: write  # อนุญาตให้ขอ OIDC token
  contents: read   # อนุญาตให้อ่าน repository

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      # Checkout โค้ดจาก repository
      - uses: actions/checkout@v4
        with:
          submodules: true

      # ตั้งค่า pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      # ตั้งค่า Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.7'
          cache: 'pnpm'

      # ติดตั้ง dependencies และ build โปรเจกต์
      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      # ตรวจสอบว่า build output มี index.html
      - name: Check build output
        run: |
          ls -la dist
          if [ ! -f "dist/index.html" ] && [ ! -f "dist/Index.html" ]; then
            echo "Error: No default file (index.html or Index.html) found in dist folder"
            exit 1
          fi

      # ตั้งค่า AWS credentials ด้วย OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::ACCOUNT_ID:role/github-actions-amplify-role  # แทนที่ด้วย ARN ของ role ที่คุณสร้าง
          aws-region: us-east-1  # ปรับ region ตามที่คุณใช้ใน Amplify
          role-duration-seconds: 3600  # เวลาที่ role จะใช้งานได้ (1 ชั่วโมง)

      # Deploy ไป AWS Amplify
      - name: Deploy to AWS Amplify
        run: |
          npm install -g @aws-amplify/cli
          amplify publish --yes
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        run: echo "Pull request closed, no deployment needed."
